### ISSUE TITLE
udatetime dependency error occur while installing rets-python library 

### ISSUE THREAD

**Issue by sohaibbt** [opendoor-labs/rets#68]
Hi, i am facing below error while  intalling this libary on local machine  however this library works fine on Google colab.
please can you help me to fix this on my local machine.

> ```
> building 'udatetime.rfc3339' extension
>   error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
>   ----------------------------------------
>   ERROR: Failed building wheel for udatetime
>     ERROR: Command errored out with exit status 1:
> ```

**Comment by nsinkov** [comment]
Fixed with https://github.com/opendoor-labs/rets/pull/67

**Comment by nsinkov** [comment]
Maybe fixed with https://github.com/opendoor-labs/rets/pull/67

**Comment by wimby** [comment]
@nsinkov How is this one? `udatetime` on version `0.0.17` seems to fix installation on linux/ubuntu for python 3.9+, however according to #59 @janwelten still have an issue on windows...

Can we bump version of rets-python, so we can install that at least on linux?

In my humble opinion there should be no python-impure compiled dependency when this library is not speed critical and especially dependency that seems to be no longer maintained...
it's better to have an (IO bound) library that is easy to use (currently rets-python is uninstallable on python 3.9+ which is quite opposite of easily usable) than faster but with a lot of effort to make it work

**Comment by bperry** [comment]
This is still an issue

`  × Running setup.py install for udatetime did not run successfully.
  │ exit code: 1
  ╰─> [38 lines of output]
      running install
      /home/bxx/.pyenv/versions/3.10.9/envs/mls-etl/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-310
      creating build/lib.linux-x86_64-cpython-310/udatetime
      copying udatetime/_pure.py -> build/lib.linux-x86_64-cpython-310/udatetime
      copying udatetime/__init__.py -> build/lib.linux-x86_64-cpython-310/udatetime
      running egg_info
      writing udatetime.egg-info/PKG-INFO
      writing dependency_links to udatetime.egg-info/dependency_links.txt
      writing top-level names to udatetime.egg-info/top_level.txt
      reading manifest file 'udatetime.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      writing manifest file 'udatetime.egg-info/SOURCES.txt'
      running build_ext
      building 'udatetime.rfc3339' extension
      creating build/temp.linux-x86_64-cpython-310
      creating build/temp.linux-x86_64-cpython-310/src
      gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -D_PYTHON3=1 -I/home/bxx/.pyenv/versions/3.10.9/envs/mls-etl/include -I/home/bxx/.pyenv/versions/3.10.9/include/python3.10 -c ./src/rfc3339.c -o build/temp.linux-x86_64-cpython-310/./src/rfc3339.o -Ofast -std=c99
      ./src/rfc3339.c: In function ‘_gettime’:
      ./src/rfc3339.c:100:18: error: storage size of ‘t’ isn’t known
        100 |     struct timeb t;
            |                  ^
      ./src/rfc3339.c:101:5: warning: implicit declaration of function ‘ftime’; did you mean ‘ctime’? [-Wimplicit-function-declaration]
        101 |     ftime(&t);
            |     ^~~~~
            |     ctime
      ./src/rfc3339.c:100:18: warning: unused variable ‘t’ [-Wunused-variable]
        100 |     struct timeb t;
            |                  ^
      ./src/rfc3339.c: At top level:
      ./src/rfc3339.c:516:21: warning: ‘CAPI’ initialized and declared ‘extern’
        516 | extern RFC3999_CAPI CAPI = {
            |                     ^~~~
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  Rolling back uninstall of udatetime
  Moving to /home/bxx/.pyenv/versions/3.10.9/envs/mls-etl/bin/bench_udatetime.py
   from /tmp/pip-uninstall-q1m2wtse/bench_udatetime.py
  Moving to /home/bxx/.pyenv/versions/3.10.9/envs/mls-etl/lib/python3.10/site-packages/udatetime-0.0.17-py3.10.egg-info
   from /home/bxx/.pyenv/versions/3.10.9/envs/mls-etl/lib/python3.10/site-packages/~datetime-0.0.17-py3.10.egg-info
  Moving to /home/bxx/.pyenv/versions/3.10.9/envs/mls-etl/lib/python3.10/site-packages/udatetime/
   from /home/bxx/.pyenv/versions/3.10.9/envs/mls-etl/lib/python3.10/site-packages/~datetime
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> udatetime`

**Comment by nsinkov** [comment]
@wimby, hi, unfortunately we will not have the cycles to look at this in the near term. Would you be able to submit a PR?

**Comment by bperry** [comment]
The version just needs bumped and published.  You guys have already changed the version dependency of udatetime to 0.0.17 which will fix this.  However the version on pypi doesn't reflect that yet.

**Comment by wimby** [comment]
@nsinkov yes, right now it's about bumping and publishing rets-python (latest version on pypi is not installable on any python 3.9+ and current master as is will work on linux python 3.9+)

long term solution that will work on windows could be getting rid of udatetime (e.g. https://github.com/opendoor-labs/rets/pull/65) or fixing udatetime on windows (they claim it's currently POSIX only library, not sure how hard is it to make it cross-platform though)
